AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP traffic to the load balancer
      VpcId: !ImportValue PicusVPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow internal traffic to ECS tasks
      VpcId: !ImportValue PicusVPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup
Outputs:
  PicusLoadBalancerSecurityGroup:
    Value: !Ref LoadBalancerSecurityGroup
    Export:
      Name: PicusLoadBalancerSecurityGroup

  PicusECSSecurityGroup:
    Value: !Ref ECSSecurityGroup
    Export:
      Name: PicusECSSecurityGroup
  