name: Build and Push to ECR

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1  

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 058264302992.dkr.ecr.eu-central-1.amazonaws.com

      - name: Build, tag, and push the Docker image
        env:
          ECR_REPOSITORY: 058264302992.dkr.ecr.eu-central-1.amazonaws.com/picus-app-repo:latest
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG -f src/Dockerfile src/
          docker push $ECR_REPOSITORY:$IMAGE_TAG

      - name: Output Image URI
        run: echo "IMAGE_URI=${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV