name: Deploy to ECS with CodeDeploy

on:
  workflow_run:
    workflows: ["Build and Push to ECR"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1  

      - name: Register new task definition with ECS
        id: task_definition
        run: |
          TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition picus-task)
          NEW_TASK_DEF=$(echo $TASK_DEFINITION | jq --arg IMAGE "$IMAGE_URI" '.taskDefinition | .containerDefinitions[0].image=$IMAGE | del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)')
          echo "$NEW_TASK_DEF" > new-task-def.json
          TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://new-task-def.json | jq -r '.taskDefinition.taskDefinitionArn')
          echo "::set-output name=task-definition-arn::$TASK_DEF_ARN"

      - name: Create appspec.yml
        run: |
          cat <<EOT >> appspec.yml
          version: 0.0
          Resources:
            - TargetService:
                Type: AWS::ECS::Service
                Properties:
                  TaskDefinition: "$TASK_DEF_ARN"
                  LoadBalancerInfo:
                    ContainerName: "picus-app"
                    ContainerPort: 80
          EOT

      - name: Upload appspec.yml to S3
        run: |
          aws s3 cp appspec.yml s3://picus-deployment-bucket/deployments/appspec.yml

      - name: Deploy to ECS using CodeDeploy
        env:
          APPLICATION_NAME: picus-ecs-application
          DEPLOYMENT_GROUP_NAME: picus-deployment-group
          NEW_TASK_DEF_ARN: ${{ env.task_definition_arn }}
        run: |
          aws deploy create-deployment \
          --application-name picus-code-deploy-PicusCodeDeployApplication-k1QqBxTe7mMQ \
          --deployment-group-name picus-deployment-group \
          --deployment-config-name CodeDeployDefault.ECSAllAtOnce \
          --revision '{"revisionType":"S3","s3Location":{"bucket":"picus-deployment-bucket","key":"deployments/appspec.yml","bundleType":"YAML"}}'